### ISSUE TITLE
Maximum file size 8 Gigabyte (8000 MB)

### ISSUE THREAD

**Issue by httsmvkcom** [redsolver/skysend#3]
![изображение](https://user-images.githubusercontent.com/51028674/103463915-f6df3100-4d40-11eb-8bcc-799276a7ba23.png)
So 8GB or unlimited?
https://skysend.hns.siasky.net/#b-ZAD8OE8NwtYKY6_G7xBeSnaE_WZkSyektnj_bNOBQ3JiaQ+9U2kuWYzcSAy4WODhCos7z7d+U3UNObRyP85bcike3ixu5IDIHjYMj/CUKYUzLmW

**Comment by redsolver** [comment]
No limit is enforced, but problems may occur with larger files (especially in the browser)

**Comment by httsmvkcom** [comment]
Understood, thank you.
